---
title: "viz_2"
output: github_document
---


```{r setup, include=FALSE}
library(ggridges)
library(patchwork)
library(tidyverse)

# these options for knitr modify how graphs come out on the output 
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

#############################################
##############All of these are default options for every figure in the rest of this doccumnet ################
#################################################

#theme_set(theme_minimal() + theme(legend.position = "bottom"))

#options(
  #ggplot2.continuous.colour = "viridis",
  #ggplot2.continuous.fill = "viridis")

#scale_colour_discrete = scale_colour_viridis_d
#scale_fill_discrete = scale_fill_viridis_d
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```

## Scatter plot but better this time 

```{r}
##positioning and axis edits
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs(
    x = "Minimum Daily Temp (C)", 
    y = "Maximum Daily Temp (C)", 
    title = "Scatterplot of daily temp extremes", 
    caption = "Data from the rnoaa package") +
  scale_x_continuous(
    breaks = c(-10, 0, 15), 
    labels = c("-10ยบ C", "0", "15")) + 
  scale_y_continuous(
    trans = "sqrt", 
    position = "right")
 
```

# Adjusting more things on the plot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    x = "Minimum Daily Temp (C)", 
    y = "Maximum Daily Temp (C)", 
    title = "Scatterplot of daily temp extremes", 
    caption = "Data from the rnoaa package") + 
  scale_color_hue(
    name = "Location", #Changes the legend name 
    h = c(100, 300))

```

```{r}
ggp_weather = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    x = "Minimum Daily Temp (C)", 
    y = "Maximum Daily Temp (C)", 
    title = "Scatterplot of daily temp extremes", 
    caption = "Data from the rnoaa package") +
   viridis::scale_color_viridis( #makes a distinct color pallet 
    name = "Location", 
    discrete = TRUE
  )

```

## Themes: changing stuff to see how it makes it look better 

```{r}
ggp_weather +
  theme_classic() + #gets rid of background 
  theme(legend.position = "bottom")
  
```

```{r}
ggp_weather +
  theme_minimal() + #gets rid of outside box 
  theme(legend.position = "bottom")
```

## Multiple dataframes on one graph 

```{r}
central_park_df = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki_df = 
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(data = waikiki_df, aes(x = date, y = tmax, color = name)) + 
  geom_point() +
  geom_line( data = central_park_df)

```

## Patchwork

```{r}
tmax_tmin_p = 
  weather_df %>% 
  ggplot(aes(x = tmax, y = tmin, color = name)) + 
  geom_point(alpha = .5) +
  theme(legend.position = "none")

prcp_dens_p = 
  weather_df %>% 
  filter(prcp > 0) %>% #get rid of days with none zero prcp
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha = .5) +
  theme(legend.position = "none")

tmax_date_p = 
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")

(tmax_tmin_p + prcp_dens_p) / tmax_date_p #need patchwork package loaded 

```


## Data manipulation 

```{r}
weather_df %>% 
  mutate(name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>% #to manually rearange the names on the x axis 
  ggplot( aes(x = name, y = tmax)) + 
  geom_boxplot()
  
weather_df %>%
  mutate(name = forcats::fct_reorder(name, tmax)) %>% #will order the names based off of the tmax vaule 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

```


```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>% 
    pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  select(id, visit, everything()) %>% 
  mutate(
    visit = fct_relevel(visit, "bl")
  )

ggplot(pulse_data, aes(x = visit, y = bdi)) + 
  geom_boxplot()

```

